config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users

  get 'page/index'
  root 'page#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true,
  format: {
      with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  }
  
  def  to_s
      "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use: :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    User.where(id: session[:user_id]).first
  end
  helper_method :current_user
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
    if current_user
        redirect_to users_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if current_user
      redirect_to users_path, notice: 'You are already logged!'
    else
      @user = User.new
    end
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to users_path, notice: 'Logged In!'
    else
        redirect_to login_path, notice: 'campos em branco'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged Out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :current_user, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    if current_user
      redirect_to users_path, notice: 'You are already logged!'
    else
      @user = User.new
    end
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user_id
      redirect_to users_path, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if current_user
      if @user.update(user_params)
        redirect_to @user, notice: 'User was successfully updated.'
      else
        render :edit
      end
    end
  end

  # DELETE /users/1
  def destroy
    unless current_user
      @user.destroy
      redirect_to users_url, notice: 'User was successfully destroyed.'
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def current_user
    User.where(id: session[:user_id]).first
  end
  helper_method :current_user
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sistema</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <p id="notice"><%= notice %></p>

    <% if current_user %>
      <%= current_user.email %>.
      <%= link_to "Log Out", logout_path %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/page/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sistema</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <header>
    <h1>oi amiguinho</h1>
  </header>
  <body>
    <div id="user_header">
      <% if current_user %>
        <%= index %>
      <% else %>
        <%= link_to signup_path do %>
          <button class="mdl-button mdl-js-button mdl-button--accent">
            Cadastro
          </button>
        <% end %>
        <%= link_to login_path do %>
          <button class="mdl-button mdl-js-button mdl-button--primary">
            Login
          </button>
        <% end %>
      <% end %>
    </div>
  </body>
</html>
<!--

<%= link_to "Login", login_path %>
-->

app/views/users/_form.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sistema</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <section>
        <div id=nav>
            <h1>Cadastro</h1>
            <%= form_with(model: user, local: true) do |form| %>
              <% if user.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

                  <ul>
                  <% user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>

              <div class="field mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <label class="mdl-textfield__label"><%= form.label :first_name %></label>
                <input class="mdl-textfield__input" type="text" <%= form.text_field :first_name %>
              </div>

              <div class="field mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <label class="mdl-textfield__label"><%= form.label :last_name %></label>
                <input class="mdl-textfield__input" type="text" <%= form.text_field :last_name %>
              </div>

              <div class="field mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <label class="mdl-textfield__label"><%= form.label :email %></label>
                <input class="mdl-textfield__input" type="text" <%= form.text_field :email %>
              </div>

              <div class="field mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <label class="mdl-textfield__label"><%= form.label :password %></label>
                <input class="mdl-textfield__input" type="password" <%= form.password_field :password %>
              </div>

              <div class="field mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <label class="mdl-textfield__label"><%= form.label :password_confirmation %></label>
                <input class="mdl-textfield__input" type="password" <%= form.password_field :password_confirmation %>
              </div>

              <div class="actions">
                  <button class="mdl-button mdl-js-button mdl-button--primary">
                      CADASTRAR
                  </button>
              </div>
            <% end %>
            <%= link_to 'Back', root_url %>
        </div>
    </section>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% if current_user == nil %>
    <p>YOU ARE DON'T LOGGED!</p>
    <%= link_to 'Back', root_url %>
<% else %>
    <h1>Listing Users</h1>
    <table>
      <thead>
        <tr>
          <th>First name</th>
          <th>Last name</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.first_name %></td>
            <td><%= user.last_name %></td>
            <td><%= link_to 'Show', user %></td>
            <td><%= link_to 'Edit', edit_user_path(user) %></td>
            <td><%= link_to 'Destroy', user, method: :delete, date: { confirm: "Are you sure?"  } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
<% end %>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<%= link_to 'Back', users_path %>